

# compatibility shim — re-export training settings for existing imports
from app_backend.config import TRAIN

# Optional: re-export common names if your scripts import symbols directly
DATASET_ROOT = TRAIN.DATASET_ROOT
INPUT_DIR    = TRAIN.INPUT_DIR
TEMP_DATA_DIR = TRAIN.TEMP_DATA_DIR
MODELS_DIR    = TRAIN.MODELS_DIR
METADATA_DIR  = TRAIN.METADATA_DIR

MODEL_SPECIES_MAP_PATH             = TRAIN.MODEL_SPECIES_MAP_PATH
GROUP_HASHES_PREV_PATH             = TRAIN.GROUP_HASHES_PREV_PATH
GROUP_HASHES_CURR_PATH             = TRAIN.GROUP_HASHES_CURR_PATH
GROUP_SPECIES_DATA_COUNT_PATH      = TRAIN.GROUP_SPECIES_DATA_COUNT_PATH
GROUP_SPECIES_DATA_COUNT_PREV_PATH = TRAIN.GROUP_SPECIES_DATA_COUNT_PREV_PATH

CONF_THRESHOLD = TRAIN.CONF_THRESHOLD
MAX_THREADS    = TRAIN.MAX_THREADS

BASE_MODEL = TRAIN.BASE_MODEL
EPOCHS     = TRAIN.EPOCHS
IMGSZ      = TRAIN.IMGSZ
BATCH      = TRAIN.BATCH

MAX_SPECIES_PER_GROUP = TRAIN.MAX_SPECIES_PER_GROUP
IMAGE_EXTENSIONS      = TRAIN.IMAGE_EXTENSIONS
TRAIN_DIR_NAME        = TRAIN.TRAIN_DIR_NAME
VALID_DIR_NAME        = TRAIN.VALID_DIR_NAME
NORMALIZE_PATTERN     = TRAIN.NORMALIZE_PATTERN

CLEAN_MODELS_DIR_BEFORE_TRAIN = TRAIN.CLEAN_MODELS_DIR_BEFORE_TRAIN





