train: ../Data/New Fish Data v2/train/images
val: ../Data/New Fish Data v2/valid/images
test: ../Data/New Fish Data v2/test/images

nc: 10
names: ['Black fin tuna thunnus atlanticus', 'Jack Crevelle Caranx Hippos', 'Largemouth Bass micropterus nigricans', 'Mahi Mahi coryphaena hippurus', 'Red Grouper Epinephelus morio', 'Red drum sciaenops ocellatus', 'Snook centropomus undecimalis', 'Yellow Tail Snapper Ocyurus chrysurus', 'spotted sea trout cynoscion nebulosus', 'tarpon megalops atlanticus']

roboflow:
  workspace: gfl
  project: fish-identification-qfctd
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/gfl/fish-identification-qfctd/dataset/2