train: ../Data/US Quarter Data v2/train/images
val: ../Data/US Quarter Data v2/valid/images
test: ../Data/US Quarter Data v2/test/images

nc: 1
names: ['George']

roboflow:
  workspace: lntech
  project: us-quarter-coin-v2
  version: 1
  license: Private
  url: https://app.roboflow.com/lntech/us-quarter-coin-v2/1